version: '3.8'

services:
  db:
    image: postgres:16-alpine 
    restart: always 
    environment: 
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. SERVICE CHO NODE.JS (Tên service: app)
  app:
    build: . # Xây dựng từ Dockerfile trong thư mục hiện tại
    restart: always
    ports:
      - "3000:3000" # Ánh xạ cổng ứng dụng
    environment: # Lấy biến môi trường từ file .env
      POSTGRES_HOST: db # RẤT QUAN TRỌNG: Tên Host là tên service DB
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: 5432
      PORT: ${PORT}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    depends_on: # Đảm bảo service DB chạy trước
      db:
        condition: service_healthy

# Định nghĩa Volume để lưu trữ dữ liệu DB
volumes:
  pgdata: